// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gobwrdkudhqobtyzmstd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvYndyZGt1ZGhxb2J0eXptc3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzQwODMsImV4cCI6MjA2NzExMDA4M30.XeHs1YyBU1uc9VApl29mjWE6wdfpr7jPeQetfvgo314";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});